version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: dbwordpress.cx4kawcai64i.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: testewordpress
      WORDPRESS_DB_NAME: db_wordpress
    volumes:
      - /data/wordpress:/var/www/html/wp-content